<?php
    $icon = 'ui-icon-info';
    $css = 'ui-state-highlight';
    switch ($this->type) {
        case Moodspin_Action_Helper_PageStatus::TYPE_MESSAGE:
            $icon = 'ui-icon-info';
            $css = 'ui-state-highlight';
            break;
        case Moodspin_Action_Helper_PageStatus::TYPE_ERROR:
            $icon = 'ui-icon-alert';
            $css = 'ui-state-error';
            break;
    } 
?>

<?php if ($this->type || $this->messageType) : ?>
	<?php if ($this->type) : ?>
	<script type="text/javascript">
	    $(document).ready(function() {
	        setTimeout(function() {
	            $('#statusMessage').slideDown();
	            setTimeout(function() {
	                $('#statusMessage').slideUp();
	            }, 10000);
	        }, 1);
	    });
	</script>
	<?php endif; ?>
<div id="statusMessage">
    <div class="ui-widget">
        <div class="<?php echo $css; ?> ui-corner-all"> 
            <p><span class="ui-icon <?php echo $icon; ?>"></span> 
            <span class="message"><?php echo $this->message; ?></span></p>
        </div>
    </div>
</div>
<?php endif; ?>