<?php

/**
 * Default Layout
 *  
 * @author
 * @version
 */

echo $this->doctype('XHTML1_TRANSITIONAL');
?>

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">

    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <?php
        $this->headTitle()->prepend($this->translate('page.title.default'));
        echo $this->headTitle();
        echo $this->headLink()->prependStylesheet('/styles/default.css')
                              ->prependStylesheet('/scripts/lib/jquery/css/smoothness/jquery-ui-1.7.2.custom.css')
                              ->appendStylesheet('/styles/mood.css')
                              ->appendStylesheet('/styles/cloud.css')
                              ->appendStylesheet('/styles/users.css')
                              ->appendStylesheet('/styles/topPeople.css')
                              ->appendStylesheet('/styles/static.css')
                              ->appendStylesheet('/styles/settings.css')
                              ->appendStylesheet('/scripts/lib/jquery/css/tooltip/tooltip.css')
                              ->appendStylesheet('/styles/ie6.css', 'all', 'lt ie 7')
                              ->appendStylesheet('/themes.style')
                              // Kampyle Css
                              ->appendStylesheet('http://cf.kampyle.com/k_button.css');
        echo $this->headStyle();

        echo $this->headScript()->prependFile('/scripts/lib/jquery/jquery-1.3.2.min.js')
                        ->appendFile('/scripts/lib/jquery/jquery-ui-1.7.2.min.js')
                        ->appendFile('/scripts/lib/jquery/plugins/jquery.limit-1.2.js')
                        ->appendFile('/scripts/lib/jquery/plugins/jquery.reject.min.js')
                        ->appendFile('/scripts/app/moodchooser.js')
                        ->appendFile('/scripts/app/loginpopup.js')
                        ->appendFile('/scripts/app/tooltips.js')
                        ->appendFile('/scripts/lib/jquery/plugins/qtip/jquery.qtip-1.0.0.min.js');
        ?>
    </head>

    <body>
        <?php echo $this->partial('partials/browser-reject.phtml'); ?>
        <?php echo $this->action('popup', 'login');?>
        <div id="page" class="wide">
            <div id="header">
                <?php echo $this->pageStatus(); ?>
                <h1><a href="/"><?php echo $this->translate('page.logo'); ?></a></h1>
                <h2><?php echo $this->translate('mood.chosser.shareYourMood'); ?></h2>
                <?php echo $this->action('index', 'navigation'); ?>
            </div>
            <div id="wrapper">
                <div id="content">
                    <div class="shadow">
                        <div class="shadow-top">
                            <div>
                                <div class=""></div>
                            </div>
                        </div>
                        <div class="shadow-left">
                            <div class="shadow-right">
                                <div class="body">
                                    <?php echo $this->layout()->content; ?>
                                </div>
                            </div>
                        </div>
                        <div class="shadow-bottom">
                            <div>
                                <div class=""></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div id="footer">
                <ul>
                    <li><a href="<?php echo $this->url(array(), 'about_us'); ?>"><?php echo $this->translate('footer.menu.aboutUs'); ?></a></li>
                    <li><a href="http://twitter.com/moodspin" target="_blank"><?php echo $this->translate('footer.menu.twitter'); ?></a></li>
                    <li><a href="<?php echo $this->url(array(), 'blog'); ?>"><?php echo $this->translate('footer.menu.blog'); ?></a></li>
                    <li><a href="<?php echo $this->url(array(), 'legal_info'); ?>"><?php echo $this->translate('footer.menu.legalInfo'); ?></a></li>
                    <li><a href="<?php echo $this->url(array(), 'help'); ?>"><?php echo $this->translate('footer.menu.help'); ?></a></li>
                </ul>
                <p><?php echo $this->translate('footer.copyright'); ?></p>
            </div>
        </div>
        <?php echo $this->partial('partials/google-analytics.phtml'); ?>
        <?php echo $this->partial('partials/kampyle-feedback.phtml'); ?>
    </body>
</html>
