<!--Start Kampyle Exit-Popup Code--> 
<script type="text/javascript">
var k_push_vars = {
     "display_after": 30,
    "view_percentage": 30,
    "popup_font_color": "#000000",
    "popup_background": "#ffffff",
    "popup_separator": "#D4E2F0",
    "header": "Your feedback is important to us!",
    "question": "Would you be willing to give us a short (1 minute) feedback?",
    "footer": "Thank you for helping us improve our website",
    "remind": "Remind me later",
    "remind_font_color": "#3882C3",
    "yes": "Yes",
    "no": "No",
    "text_direction": "ltr",
    "images_dir": "http://cf.kampyle.com/",
    "yes_background": "#76AC78",
    "no_background": "#8D9B86",
    "site_code": 5892825
}
</script>
<!--End Kampyle Exit-Popup Code-->


<!--Start Kampyle Feedback Form Button--><div id="k_close_button" class="k_float kc_bottom kc_right"></div><div><a href="http://www.kampyle.com/solutions/customer-feedback-form/"  target="kampyleWindow" id="kampylink" class="k_float k_bottom k_right" onclick="javascript:k_button.open_ff('site_code=5892825&amp;form_id=36712&amp;lang=en');return false;"><img src="http://cf.kampyle.com/buttons/en/blue/en-blue-corner-low-right.gif" alt="Feedback Form" border="0"/></a></div><div id="k_slogan" class="k_float k_bottom k_right"></div><script src="http://cf.kampyle.com/k_button.js" type="text/javascript"></script>
<script type="text/javascript" src="http://cf.kampyle.com/k_push.js"></script><!--End Kampyle Feedback Form Button-->
