<?php
$this->headTitle('Moodspin Users\' List');
$this->headScript()->appendFile('/scripts/lib/jquery/plugins/jquery.tablesorter.js');
$this->headLink()->appendStylesheet('/scripts/lib/jquery/css/tablesorter/style.css');
$this->headScript()->appendFile('/scripts/app/users.js');
$this->headLink()->appendStylesheet('/styles/users.css');
?>
<script type="text/javascript"><!--
$(function() {
    var app = new Users({
    	'simple' : true
    });
    app.init();
});
//-->
</script>
<form id="filterForm" action="" method="post">
    <input type="hidden" name="page" value="<?php echo $this->page; ?>" />
    <input type="hidden" name="sort" value="<?php echo $this->sort; ?>" />
    <input type="hidden" name="sort_order" value="<?php echo $this->sortOrder; ?>" />
</form>
<table id="registeredUsersTable" class="tablesorter">
    <thead>
        <tr>
            <th class="sortable" sort="login">Twitter Name</th>
            <th class="sortable" sort="creation_date">Joined Moodspin</th>
            <th class="sortable" sort="followers_on_moodspin">Followers on moodspin</th>
            <th class="sortable" sort="following_on_moodspin">Following on moodspin</th>
        </tr>
    </thead>
    <tfoot>
        <tr>
            <th>Twitter Name</th>
            <th>Joined Moodspin</th>
            <th>Followers on moodspin</th>
            <th>Following on moodspin</th>
        </tr>
    </tfoot>
    <tbody>
        <?php foreach ($this->users as $user) : ?>
        <tr>
            <td><a href="http://twitter.com/<?php echo $user['login'] ?>"><?php echo $user['login'] ?></a></td>
            <td><?php echo $user['creation_date']; ?></td>
            <td><?php echo $user['followers_on_moodspin'] ?></td>
            <td><?php echo $user['following_on_moodspin'] ?></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<div align="center">
    <?php echo $this->paginationControl($this->users, 'Sliding', 'paging.phtml'); ?>
</div>