<?php
$this->headTitle('Potential Users\' List');
$this->headLink()->appendStylesheet('/scripts/lib/jquery/css/tablesorter/style.css');
$this->headScript()->appendFile('/scripts/app/messenger.js');
$this->headScript()->appendFile('/scripts/app/users.js');
$this->headLink()->appendStylesheet('/styles/users.css');
?>

<script type="text/javascript">
<!--
$(function() {
    $('#filterForm .date:input').datepicker({
        dateFormat: 'yy-mm-dd'
    });
    var app = new Users(
        {
        	'consts' : {
	            MESSAGE_MAX_LENGTH : 140
	        },
	        'urls' : {
	            URL_FOLLOW : '/admin/index/follow/',
	            URL_SEND_MESSAGE : '/admin/index/send-message/'
	        },
	        'messages' : {
	            ERROR_FOLLOW   : "<?php echo $this->translate('userlist.error_follow') ?>",
	            ERROR_UNFOLLOW : "<?php echo $this->translate('userlist.error_unfollow') ?>",
	            OK_FOLLOW      : "<?php echo $this->translate('userlist.ok_follow') ?>",
	            OK_UNFOLLOW    : "<?php echo $this->translate('userlist.ok_unfollow') ?>",
	            ERROR_SEND_MESSAGE : "<?php echo $this->translate('userlist.error_send_message') ?>",
	            OK_SEND_MESSAGE    : "<?php echo $this->translate('userlist.ok_send_message') ?>"
	        },
            'moods' : <?php echo $this->moods ? Zend_Json::encode($this->moods) : '[]'; ?>
        }
    );
    app.init();
});
//-->
</script>

<form id="filterForm" action="" method="post">
    <input type="hidden" name="page" value="<?php echo $this->page; ?>" />
    <input type="hidden" name="sort" value="<?php echo $this->sort; ?>" />
    <input type="hidden" name="sort_order" value="<?php echo $this->sortOrder; ?>" />
    <div id="moodContainer" class="leftFloat">
        <ul>
	        <?php foreach ($this->moodCategories as $moodCategory) : ?>
	            <li><span class="mood_category_name"><?php echo $moodCategory['category']['name'] ?></span>
	               <ul>
			            <?php foreach ($moodCategory['moods'] as $mood) : ?>
			                <li>
                                <div class="mood">
                                    <img src="/images/moods/mood_<?php echo $mood->id; ?>.png" />
                                    <input id="mood_<?php echo $mood->id ?>" type="checkbox" name="moods[]" value="<?php echo $mood->id; ?>" />
                                </div>
                            </li>
			            <?php endforeach; ?>
	                </ul></li>
	        <?php endforeach; ?>
        </ul>
        <button class="resetMoods">Reset Moods</button>
    </div>
    <div class="leftFloat">
        <span># of followers</span>
        <input name="minFollowers" value="<?php echo $this->minFollowers ?>" /> to <input name="maxFollowers" value="<?php echo $this->maxFollowers ?>" />
    </div>
    <div class="leftFloat">
	    <ul>
	        <li>
	            <label for="from_date">From:</label>
	            <input class="date" type="text" id="from_date" name="from_date" value="<?php echo $this->form->getValue('from_date')?>" />
	        </li>
	        <li>
	            <label for="to_date">To:</label>
	            <input class="date" type="text" id="to_date" name="to_date" value="<?php echo $this->form->getValue('to_date')?>" />
	        </li>
	        <li>
	            <input type="submit" value="Go" />
	        </li>
	    </ul>
    </div>
</form>

<div class="usersSelectAllContainer">
    <button class="usersSelectAll">Select All</button>
</div>
<table id="registeredUsersTable" class="tablesorter">
    <thead>
        <tr>
            <th class="sortable" sort="login">Name</th>
            <th class="sortable" sort="followers_num"># Followers</th>
            <th class="sortable" sort="following_num"># Following</th>
            <th>Latest mood status</th>
            <th class="sortable" sort="latest_status_date">Tweet date</th>
            <th class="sortable" sort="contacted_date">Invited on</th>
            <th class="sortable" sort="moodspin_following">@moodspin following</th>
            <th>Select for action</th>
        </tr>
    </thead>
    <tfoot>
        <tr>
            <th>Name</th>
            <th># Followers</th>
            <th># Following</th>
            <th>Latest mood status</th>
            <th>Tweet date</th>
            <th>Invited on</th>
            <th>@moodspin following</th>
            <th>Select for action</th>
        </tr>
    </tfoot>
    <tbody>
        <?php foreach ($this->users as $user) : ?>
        <tr>
            <td>
                <a href="http://twitter.com/<?php echo $user['login'] ?>" target="_blank">
                    <?php echo $user['login'] ?>
                </a>
            </td>
            <td><?php echo $user['followers_num'] ?></td>
            <td><?php echo $user['following_num'] ?></td>
            <td><?php echo htmlspecialchars($user['latest_status_message']) ?></td>
            <td><?php echo $user['latest_status_date']; ?></td>
            <td><?php echo $user['contacted_date']; ?></td>
            <td><?php echo $user['moodspin_following'] ?
                $this->translate('userlist.yes') : $this->translate('userlist.no') ?></td>
            <td><input type="checkbox" name="<?php echo $user['login'] ?>" value="<?php echo $user['twitter_id'] ?>" /></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<div class="usersSelectAllContainer">
    <button class="usersSelectAll">Select All</button>
</div>
<div align="center">
    <?= $this->paginationControl($this->users, 'Sliding', 'paging.phtml'); ?>
</div>

<div class="actionsContainer">
    <div class="usersFollowing">
        <h2>Follow</h2>
        <button class="buttonFollowUser">Make @moodspin to follow selected people</button>
        <button class="buttonUnFollowUser">Make @moodspin to UNFOLLOW selected people</button>
    </div>
    <div class="usersSending">
        <h2>Send message</h2>
        <div class="leftFloat">
            <textarea class="messageText"></textarea>
        </div>
        <div class="leftFloat">
            <button class="messageSend">Send</button>
        </div>
        <div class="clear"></div>
        <p><span class="messageCharsLeft">140</span> Characters left</p>
    </div>
</div>