<?php

/**
 * About Us page view
 *
 * @author
 * @version
 */

$this->headTitle($this->translate('page.title.aboutUs'));
?>

<table width="100%" border="0" align="left">
<tr>
<td width="100%" valign="top"><h3>About Us</h3>
<div id="staticpage">
<p>
Twitter is asking, "What are you doing?"<br />
The folks at Facebook want you to share "What's on your mind?" <br /><br />
moodspin is all about <b>how you feel</b> and <b>what are you craving</b>.<br />
</p><br />
<p>
moodspin believes that people should be able to express themselves in a fun and easy way. With moodspin, you can go beyond text messages to share your feelings and moods with your friends using colors, emoticons and more. moodspin is also a great way to easily see how your friends are feeling, connect with friends in the same mood or reach out to friends who need your attention.
</p>
<h4>
Are you in the mood? Express Yourself!
</h4>
<p>
Just log in <b>using your Twitter account,</b> choose a color or an icon that suits your mood and share it with your friends. moodspin will modify your profile image, allowing all your friends to see your mood, even if they missed your latest text update. 
</p>
<p>
Track your mood and notice when your friends are changing their mood.
</p>
<p>
This is just the beginning. We have a ton of cool stuff on the way!
</p>
<p>
In the mood to help?!<br />
Contact us <a href="mailto:info@moodspin.com">info@moodspin.com</a> and
follow us on <a href="http://twitter.com/moodspin">Twitter</a>
and <a href="http://www.facebook.com/pages/moodspin/104927371444">Facebook</a>.
</p>
</div>
		</td>
<td width="50px"></td>
<td width="320px" valign="top">
<script type="text/javascript" src="http://static.ak.connect.facebook.com/js/api_lib/v0.4/FeatureLoader.js.php/en_US"></script>
<script type="text/javascript">FB.init("9281a296432256b2ee0665317534959a");</script>
<fb:fan profile_id="104927371444" stream="1" connections="10" width="300"></fb:fan>
<div style="font-size:8px; padding-left:10px"><a href="http://www.facebook.com/pages/moodspin/104927371444">moodspin on Facebook</a> </div> 
</td>
</tr>
</table>


