<?php

/**
 * Help Page view
 *
 * @author
 * @version
 */

$this->headTitle($this->translate('page.title.help'));
?>
<div id="staticpage" style="width: 70%;">
<h3>Check these common questions and answers.</h3>
<p>
In case you still have questions, simply contact us on Twitter (<a href="http://twitter.com/moodspin" target="_blank">@moodspin</a>), <a href="http://www.facebook.com/pages/moodspin/104927371444">Facebook</a> or send us an <a href="mailto:support@moodspin.com">eMail</a>.
</p>
<p><a href="#moodspincom">moodspin.com</a> | <a href="#iphone">iPhone application</a> | <a href="#mood-badge">Mood Badge</a> | <a href="#facebook">Facebook</a></p>
<h3 id="moodspin.com">moodspin.com</h3>
<h4>How do I create a moodspin.com account?</h4>
<p>Every Twitter user can have a moodspin.com account.
Just use the "login with Twitter" link on the top right corner to login to Twitter, and you are all set.
</p>

<h4>Can I use moodspin.com with my Facebook account?</h4>
<p>
moodspin.com works with your Twitter account. For Facebook you can use the mood-badge to share your mood, as set on moodspin.com or use the <a href="http://apps.facebook.com/moodspin/" target="_blank">moodspin Facebook application</a>.

<h4>How do I share my mood?</h4>
<p>Simply select an emoticon or a color that matches your mood from the drop down menus below the status text area. The status text area will be automatically filled with our default comment, which you can modify or add to. Click "Update" and you are done.</p>

<h4>Can I choose other colors or icons?</h4>
<p>
We are working on adding more icons and colors to the list. Please share with us what would you like to see on <a target="_blank" href="http://twitter.com/moodspin">Twitter (@moodspin)</a> or <a href="http://www.facebook.com/pages/moodspin/104927371444">Facebook</a>.
</p>
<h4>I want to reset my image - how do I do that?</h4>
<p>Simply click the "Reset Image" link bellow the image and your image will be reset to the original version. An alternative would be to upload a new/another image directly to Twitter/Facebook.
</p>
<h4>I just uploaded a new image to Twitter but I don't see the update in moodspin.com, why is that?</h4>
<p>This is a known issue with Twitter's API. The image we received via Twitter's API is cached for 3 hours, so you may not see your latest image immediately. We are working with Twitter to address this issue.
</p>
<h4>Can I Follow / ReTweet / Reply using moodspin?</h4>
<p>Sure, just hover on the person status update and use the buttons to perform the action. Currently, you will be redirected to Twitter to complete the "Follow" action, but we are working on allowing you to do that on moodspin...</p>

<h4>How can I sort people based on their moods?</h4>
<p>In the "Everyone" tab, use the "Mood Cloud" to view people in a specific mood. The list is in an alphabetic order.</p>

<p>For sorting people in your network, use "FRIENDS" and select the relevant moods from the filter list.</p>

<h4>Can I add more moods to the "Mood Cloud"?</h4>
<p>Currently we are supporting only the listed moods, but we are working on adding more moods for you express yourself.</p>
<p>Please let us know which moods you think we should add. Contact us on <a target="_blank" href="http://twitter.com/moodspin">Twitter (@moodspin)</a> or <a href="http://www.facebook.com/pages/moodspin/104927371444">Facebook</a>.
</p>

<h4>How do I share my feedback with you?</h4>
<p>Thank you for your wiliness to share your feedback with us. Please use the feedback button (bottom right corner). You can also send us a message on <a target="_blank" href="http://twitter.com/moodspin">Twitter (@moodspin)</a> or <a href="http://www.facebook.com/pages/moodspin/104927371444">Facebook</a>.

<h4>Can I update moodspin.com and Twitter from my iPhone?</h4>
<p>Yes. Just <a target="_blank" href="http://appsto.re/moodspin">download </a> the moodspin iPhone application for free.
</p>
<a href="#page">Back to top</a>
<hr/>
<h3 id="iphone">iPhone application</h3>
<h4>Where can I get the iPhone application?</h4>
<p>moodspin iPhone application is available on the <a target="_blank" href="http://appsto.re/moodspin"> iTunes store </a> for free.</p>

<h4>If I update my mood using the iPhone application, will it update my mood on moodspin.com as well?</h4>
<p>Yes it will. Just log in using your <b>Twitter account</b>.</p>
<a href="#page">Back to top</a>
<hr/>
<h3 id="mood-badge">Mood Badge</h3>
<p>We are using the <a href="http://www.clearspring.com/">http://www.clearspring.com/</a> platform to share the mood badge. You can place the mood badge on all major social network sites as well as on your blog and iGoogle.</p>
<h4>Why does the mood badge seem blank in the preview?</h4>
<p>The mood badge is personalized and retrieves your mood status and profile image in real-time, so it may take a sec before you can see all the data. Some social network sites create a preview without retrieving all the data. Don't worry - your image and status will be visible to your friends when they view your page.</p>
<a href="#page">Back to top</a>
<hr/>
<h3 id="facebook">Facebook</h3>
<h4>How can I share my mood on Facebook?</h4>
<p>
Currently you can use the mood badge to share your mood from moodspin.com on Facebook. Or, you could use the
<a href="http://apps.facebook.com/moodspin/" target="_blank">moodspin Facebook application</a>
.
</p>
<h4>I cannot access the moodspin Facebook application</h4>
<p>
The moodspin Facebook application requires cookies enabled browser. Follow <a href="http://www.google.com/support/websearch/bin/answer.py?hl=en&amp;answer=35851" target="_blank">these steps</a> to enable cookies for your browser.
</p>
<a href="#page">Back to top</a>
</div>