<?php

/**
 * Admin Layout
 *  
 * @author
 * @version
 */

echo $this->doctype('XHTML1_TRANSITIONAL');
?>

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">

    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <?php
        echo $this->headTitle($this->translate('page.title.default'));
        echo $this->headScript()->prependFile('/scripts/lib/jquery/jquery-1.3.2.min.js')
                                ->appendFile('/scripts/lib/jquery/jquery-ui-1.7.2.min.js')
                                ->appendFile('/scripts/lib/jquery/plugins/jquery.limit-1.2.js')
                                ->appendFile('/scripts/lib/jquery/plugins/jquery.form.js')
                                ->appendFile('/scripts/lib/jquery/plugins/jquery.loadmask.min.js');
        echo $this->headLink()->prependStylesheet('/scripts/lib/jquery/css/smoothness/jquery-ui-1.7.2.custom.css')
                              ->prependStylesheet('/scripts/lib/jquery/css/loadmask/jquery.loadmask.css')
                              ->prependStylesheet('/styles/admin.css')
                              ->prependStylesheet('/styles/messenger.css');
        echo $this->headStyle();
        ?>
        <!--[if lt IE 7]><style type="text/css" media="screen">
            body {
                behavior: url('/styles/csshover3.htc');
            }
        </style><![endif]-->
    </head>

    <body>
        <div id="page">
            <div id="wrapper">
                <div id="content">
					<?php echo $this->pageStatus(); ?>
                    <?php if($this->placeholder('navigation')!='hidden'):?>
					<p>
                        <a href="/admin/index/">Dashboard</a> | 
                        <a href="/admin/index/registered-users">Registered Users</a> |
                        <a href="/admin/index/potential-users">Potential Users</a> |
                        <a href="/admin/index/moodspin-users">Moodspin Users</a> |
                        <a href="/admin/index/send-messages">Send messages</a> |
                        <a href="/admin/index/moods">Moods</a> |
                        <a href="/admin/chart">Users Chart</a> |
                        <a href="/admin/chart/moods">Moods Chart</a> |
                        <a href="/admin/security/logout">Logout</a>
                    </p>
                    <?php endif;?>
                    <?php echo $this->layout()->content; ?>
                </div>
            </div>
        </div>
    </body>
</html>