<div id="news">
	<ul>
		<li class="facebook">
		    <a href="http://apps.facebook.com/moodspin/" target="_blank">
		        <img src="/images/static/facebook-logo.png" alt="" />
		    </a>
			<h4>
				<a href="http://apps.facebook.com/moodspin/" target="_blank">
					Moodspin on Facebook
				</a>
			</h4>
			<p>
                <span class="fb_profile_connect">
                    <a class="UIButton UIButton_Gray UIActionButton" href="http://www.facebook.com/pages/moodspin/104927371444" target="_blank">
                        <span class="UIButton_Text">
                            <span class="UIButton_Icon UIButton_IconNoSpriteMap" style="background-position: 0 -7px;"></span>
                            Become a Fan
                        </span>
                    </a>
                </span>
			</p>
		</li>
		<li class="iphone">
		    <a href="/iPhone.html">
		        <img src="/images/news/iphone.png" alt="" />
		    </a>
			<h4>
                <a href="/iPhone.html">
                    On-the-move?
                </a>
			</h4>
			<p>Share your mood with 3 clicks using the moodspin iPhone application.</p>
		</li>
	</ul>
</div>