<?php
$this->layout()->setLayout('page');
$this->headTitle()->set('get badge');
?>

<div id="staticpage">
	<div style="float: right; margin-left: 10px;">
		<object width="421" height="171" type="application/x-shockwave-flash" quality="high" id="W4aeb23aab0e89b0c" data="http://widgets.clearspring.com/o/4ab91a3fc5d4c8c9/4aeb23aab0e89b0c/4ab91a3fc5d4c8c9/22129755/username/<?php echo $this->username?>">
			<param value="http://widgets.clearspring.com/o/4ab91a3fc5d4c8c9/4aeb23aab0e89b0c/4ab91a3fc5d4c8c9/22129755/username/<?php echo $this->username?>" name="movie"/>
			<param name="wmode" value="transparent"/>
			<param name="allowScriptAccess" value="always"/>
			<param name="allowNetworking" value="all"/>
		</object>
	</div>

	<h3>Share everywhere</h3>
	<p>
	Use the mood-badge to share your mood everywhere.
	Simply click the "Get & Share link" and choose the destination.
	Now all your friends can see how you feel in all of thefollowing sites and services:
	</p>
	
	<div style="width: 100%; text-align: right;">
		<img alt="Badge Network" src="/images/static/badge-network.png" style="margin: 20px;" />
	</div>
</div>