<?php

/**
 * User's moodline page
 *
 * @author
 * @version
 */

$this->headTitle($this->translate('page.title.moodline'));
$this->placeholder('tab')->set('moodline');
?>

<div id="moodline">

<div class="date">
	<div>
		<a class="prev" href="#">&lt;</a>
		<span class="date-interval"></span>
		<a class="next" href="#">&gt;</a>
	</div>
</div>

<div class="avatar">
	<?php if($this->showAvatar != null):?>
	<img src="<?php echo $this->showAvatar ?>" alt="<?php echo $this->user ?>" />
	<?php endif; ?>
</div>

<table>
<thead>
	<tr>
		<td></td>
		<th>12AM</th>
		<th>2AM</th>
		<th>4AM</th>
		<th>6AM</th>
		<th>8AM</th>
		<th>10AM</th>
		<th>12PM</th>
		<th>2PM</th>
		<th>4PM</th>
		<th>6PM</th>
		<th>8PM</th>
		<th>10PM</th>
		<th>12AM</th>
	</tr>
</thead>
<tbody>
	<tr>
		<th><span>Sunday</span></th>
		<td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td>
	</tr>
	<tr>
		<th><span>Monday</span></th>
		<td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td>
	</tr>
	<tr>
		<th><span>Tuesday</span></th>
		<td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td>
	</tr>
	<tr>
		<th><span>Wednesday</span></th>
		<td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td>
	</tr>
	<tr>
		<th><span>Thursday</span></th>
		<td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td>
	</tr>
	<tr>
		<th><span>Friday</span></th>
		<td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td>
	</tr>
	<tr>
		<th><span>Saturday</span></th>
		<td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td>
	</tr>
</tbody>
</table>

<div class="markers"></div>

</div>
<!-- <pre id="debug" style="overflow:scroll;">
</pre>-->
<script type="text/javascript">
	$(document).ready(function(){
		$('#moodline').moodline({serviceUrl:"/mood-line/",user:"<?php echo $this->user?>"});
	});
</script>